### ISSUE TITLE
Upgrade rect-native to latest - 0.71

### ISSUE THREAD

**Issue by shehand** [scorelab/Go-social#162]
## Prerequisites

- Dependencies should be align with RN version.

## Expected Behavior

The app should be working (at least the login/singin page and dashboard view should be rendered)

## Current Behavior

App is outdated because of RN version and the dependencies should be upgraded too

**Comment by shehand** [comment]
Anyone interested on this, please comment and I will assign the issue

**Comment by vedant-3010** [comment]
Hello shehand , I am interested, can you assign it to me ?

**Comment by ajaman190** [comment]
Hello @shehand is this issue resolved, I would like to contribute to it.

**Comment by shehand** [comment]
@ajaman190 please go for it.

**Comment by ajaman190** [comment]
Hey @shehand , I'm happy to let you know that I've successfully upgraded the **Go_social** app's React Native version from **0.58.6** to **0.71.3**. This upgrade involved significant changes in both versions, many aspects of the app required updating. 

![Screenshot 2023-03-07 083343](https://user-images.githubusercontent.com/84832565/223313342-e66191d5-1917-45ff-a588-28a60beebcfd.png)

Now the app is building smoothly without any errors. However, there are still some dependencies that need attention, such as AsyncStorage, React-Navigation, and react-native-map, etc. These dependencies have undergone changes that need to be addressed. 

![Screenshot 2023-03-07 083436](https://user-images.githubusercontent.com/84832565/223313501-506d9178-1091-45de-b6e7-13a4aa5a46ca.png)


At present, I'm encountering a Firebase error, which I believe is due to the absence of the config.js file in the config folder. Currently, there's only a config.example.js file available if config folder. If I can obtain the config.js file, I can move forward with addressing the aforementioned issues.

![Screenshot 2023-03-07 083230](https://user-images.githubusercontent.com/84832565/223313542-ec504225-5057-4afe-a9c5-1eb95689a15b.png)

**Comment by shehand** [comment]
@ajaman190 you ned to rename example file as config.js and move forward. Please refer the readme file for further instructions.

**Comment by ajaman190** [comment]
Sure

**Comment by ajaman190** [comment]
"Hi @shehand, I'm submitting a PR for this. Could you please assign me this issue so that I can raise a PR for **GSOC23**?"

**Comment by ajaman190** [comment]
@shehand  Kindly review the PR and assign me of any other issues that need to be addressed.

**Comment by shehand** [comment]
@ajaman190 you can work on #163 as the follow up issue.
